# Latex-Online container
#
# VERSION       1

# use the ubuntu base image provided by dotCloud
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive 

RUN apt-get update && \
    apt-get install -y --no-install-recommends tzdata gcc 

# Install git & Node.JS
RUN apt-get clean && apt-get update && apt-get install -y git-core nodejs npm 

# Sorted list of used packages.
RUN apt-get clean && apt-get update && apt-get install -y \
    biber \
    cm-super \
    cm-super \
    fontconfig \
    git-core \
    texlive-latex-recommended \
    preview-latex-style \
    python3 \
    texlive-bibtex-extra \
    texlive-fonts-extra \
    texlive-plain-generic \
    texlive-lang-all \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-publishers \
    texlive-science \
    texlive-xetex && \
    rm -rf /var/lib/apt/lists/*



# Add xindy-2.2 instead of makeindex.
ADD ./packages/xindy-2.2-rc2-linux.tar.gz /opt
ENV PATH="/opt/xindy-2.2/bin:${PATH}"

COPY ./util/docker-entrypoint.sh /

EXPOSE 2700
CMD ["./docker-entrypoint.sh"]

